# Generated by Django 4.2.7 on 2025-08-13 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free'), ('other', 'Other')], default='other', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_response', models.JSONField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_subscriptions',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['student', 'payment_status'], name='course_subs_student_9315d0_idx'), models.Index(fields=['course', 'payment_status'], name='course_subs_course__a691a0_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
