# Generated by Django 4.2.7 on 2025-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_purchased_courses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, max_length=13),
        ),
    ]
