# Generated by Django 4.2.7 on 2025-08-17 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='teacherprofile',
            name='teacher_pro_user_id_ffcba3_idx',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by admin'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='teacher_resumes/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.JSONField(default=list, help_text='List of subjects/areas of expertise'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief professional biography'),
        ),
    ]
