# Generated by Django 4.2.7 on 2025-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='advantages',
            field=models.JSONField(default=list, help_text='List of course advantages/features'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(default=30, help_text='Total course duration in hours'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_active'], name='courses_categor_424be0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_slug_360be0_idx'),
        ),
    ]
